M48
; DRILL file {KiCad 7.0.10} date Sat Apr 13 19:06:13 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-13T19:06:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
%
G90
G05
T1
X112.075Y-139.12
X116.925Y-139.12
T2
X111.775Y-142.15
X117.225Y-142.15
T3
X102.3Y-147.75
X143.7Y-147.95
X144.272Y-37.465
T4
X141.986Y-68.263
M30
